using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

//Each new term in the Fibonacci sequence is 
//generated by adding the previous two terms.By starting with 1 and 2, the first 10 terms will be:

//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

//By considering the terms in the Fibonacci 
//sequence whose values do not exceed four million, find the sum of the even-valued terms.

namespace FibonacciSumEven
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            CreateFibonacci(0, 1, 2);

            string elements = "";

            foreach (int element in FibArray){

                elements = elements + element.ToString() + ",";
            }
            MessageBox.Show(elements);


            fibSumOfEven(1);
            MessageBox.Show(sum_.ToString());
            ;
        }

        int[] FibArray =new int[13];
        public int sum_ = 0;
        public void fibSumOfEven(int n)
        {
            if (n >= FibArray.Length)
            {
                return;
            }

            if (FibArray[n] % 2 == 0)
            {
                sum_ = sum_ + FibArray[n];
            }

            ;

            fibSumOfEven(n + 1);

        }

        int pointer = 2;

        public void CreateFibonacci(int val1, int val2, int n )
        {
            FibArray[n - 2] = val1;
            FibArray[n - 1] = val2;

            int newnum = val1 + val2;

            if (newnum > 100)//400000000
            {
                return;
            }
            CreateFibonacci(val2, newnum, n+1);
        }
    }
}
